embeddings:
  model: "law-ai/InLegalBERT"
  dimension: 768
  device: "cpu"

retrieval:
  chunk_size: 512
  chunk_overlap: 200
  top_k: 5
  index_type: "IndexFlatIP"  # FAISS index type (can be IndexFlatIP, IndexIVFFlat, etc.)
  data_dir: "data/processed/faiss"  # Directory to store FAISS indices
  nlist: 100  # Number of clusters for IVF indices (if used)

generation:
  model: "google/gemma-1b-it"
  max_new_tokens: 256
  temperature: 0.7
  device: "cpu"

api:
  host: "0.0.0.0"
  port: 8000